#!/usr/bin/env python3
#
# curtin-hooks - Curtin installation hooks for Ubuntu
#

import os
import shutil

from curtin.commands.curthooks import builtin_curthooks
from curtin.config import load_command_config
from curtin.util import load_command_environment


def configure_custom_kernel(config):
    """Amend the curtin config to explicity specify the kernel to install.

    The name of the kernel to install should already have been written to the
    CUSTOM_KERNEL file in the same directory as this file.
    """
    custom_kernel_path = os.path.join(
        os.path.dirname(__file__), "CUSTOM_KERNEL")
    with open(custom_kernel_path, "r") as custom_kernel_file:
        custom_kernel_package = custom_kernel_file.read().strip()
    kernel_config = config.setdefault("kernel", {})
    kernel_config["package"] = custom_kernel_package
    return config


def cleanup():
    """Remove curtin-hooks so its as if we were never here."""
    curtin_dir = os.path.dirname(__file__)
    shutil.rmtree(curtin_dir)


def main():
    state = load_command_environment()
    config = load_command_config(None, state)
    target = state['target']

    config = configure_custom_kernel(config)
    builtin_curthooks(config, target, state)
    cleanup()


if __name__ == "__main__":
    main()
