[tool.black]
line-length = 79
# VMware ESXi 6.7 uses Python 3.5
# VMware ESXi 7.0 uses Python 3.8
target-version = ["py35", "py38"]

[tool.isort]
from_first = false
profile = "black"
line_length = 79
