#cloud-config
autoinstall:
  early-commands:
    - wget http://172.22.31.150/scripts/harmonic-installer.sh -O /tmp/harmonic-installer.sh
    - chmod +x /tmp/harmonic-installer.sh
    - /tmp/harmonic-installer.sh
runcmd:
  - echo "---------------- Harmonic Installer - Update Sudoers (Add 'ubuntu' user with 'ALL=(ALL) NOPASSWD:ALL') -----------------"
  - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu
  - echo "---------------- Harmonic Installer - Configure SSHd (Allow Root Login) -----------------"
  - sed -i -e '/^[#]*PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - echo "---------------- Harmonic Installer - Configure SSHd (Allow Password Login) -----------------"
  - sed -i -e '/^[#]*PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - echo "---------------- Harmonic Installer - Setup (RESTARTING SSHd) -----------------"
  - systemctl restart ssh
bootcmd:
  - echo "---------------- Harmonic Installer - Discovery (Filesystems and Mounts) -----------------"
  - pwd
  - df -h
  - ls -alh /
  - ls -alh /root
  - ls -alh /target
  - ls -alh /media
  - ls -alh /usr/local/bin
  - ls -alh /etc/systemd/system
  - ls -alh /data
  - ls -alh /run
  - ls -alh /opt
  - ls -alh /tmp
  - echo "---------------- Harmonic Installer - Install Script (DOWNLOAD) -----------------"
  - wget http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /media/root-rw/harmonic-installer.sh
  - chmod +x /media/root-rw/harmonic-installer.sh
  - echo "---------------- Harmonic Installer - Install Script (RUNNING) -----------------"
  - /media/root-rw/harmonic-installer.sh
  - echo "------------------- Harmonic Installer - Install Script (COMPLETED) ------------------"
