#cloud-config
users:
  - name: ubuntu
    lock_passwd: False
    password: $6$canonical.$0zWaW71A9ke9ASsaOcFTdQ2tx1gSmLxMPrsH0rF0Yb.2AEKNPV1lrF94n6YuPJmnUy2K2/JSDtxuiBDey6Lpa/
    ssh_redirect_user: False
    ssh_pwauth: True
disable_root: False
preserve_hostname: False
runcmd:
  - |
    echo "==================================================================="
    echo "Harmonic Installer: Setup"
    echo "==================================================================="
    echo "Harmonic Installer: Update resolver"
    echo "==================================================================="
    cat < EOF >/etc/resolv.conf
    echo "Harmonic Installer: Downloading 'harmonic-installer.sh'"
    echo "==================================================================="
    if (sudo wget https://artifactory.charterlab.com:443/artifactory/upload/harmonic/scripts/harmonic-installer.sh -O /opt/harmonic-installer.sh && sudo chmod +x /opt/harmonic-installer.sh); then
      echo "Harmonic Installer: Running"
      else
      echo "Harmonic Installer: Failed to download 'harmonic-installer.sh'"
      exit 1
      fi
    echo "==================================================================="
    if (sudo /opt/harmonic-installer.sh -ip); then
      echo "==================================================================="
      echo "Harmonic Installer: Installation Complete"
      else
      echo "==================================================================="
      echo "Harmonic Installer: Installation Failed"
      exit 1
      fi
