#cloud-config
users:
  - name: ubuntu
    lock_passwd: False
    password: $6$canonical.$0zWaW71A9ke9ASsaOcFTdQ2tx1gSmLxMPrsH0rF0Yb.2AEKNPV1lrF94n6YuPJmnUy2K2/JSDtxuiBDey6Lpa/
    ssh_redirect_user: False
    ssh_pwauth: True
disable_root: False
preserve_hostname: False
runcmd:
  - |
    echo "=====================================================================================" \
    && echo "Harmonic Installer: Setup" \
    && echo "=====================================================================================" \
    && echo "Harmonic Installer: Download 'harmonic-installer.sh' from Artifactory" \
    && sudo wget https://artifactory.charterlab.com:443/artifactory/upload/harmonic/scripts/harmonic-installer.sh -O /opt/harmonic-installer.sh \
    && sudo chmod +x /opt/harmonic-installer.sh \
    && echo "=====================================================================================" \
    && echo "Harmonic Installer: Running" \
    && sudo /opt/harmonic-installer.sh -vip \
    && echo "=====================================================================================" \
    && echo "Harmonic Installer: Complete" \
    && echo "=====================================================================================" \
    && echo "Harmonic Installer: Rebooting System" \
    && sudo systemctl --message="Harmonic Post-Install Reboot" reboot