#cloud-config
users:
  - name: ubuntu
    lock_passwd: False
    plain_text_passwd: ubuntu
    ssh_redirect_user: False
    ssh_pwauth: True
    disable_root: False
    preserve_hostname: False
runcmd:
  - echo "---------------- Harmonic Installer - Fix root authorized_keys  -----------------"
  - sudo sed -r -i 's/^.+(ssh-.+)$/\1/' /root/.ssh/authorized_keys  
  - echo "---------------- Harmonic Installer - Create working directory -----------------"
  - echo "---------------- Harmonic Installer - Install Script (DOWNLOAD) -----------------"
  - wget http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /tmp/harmonic-installer.sh
  - chmod +x /tmp/harmonic-installer.sh
  - echo "---------------- Harmonic Installer - Install Script (RUNNING) -----------------"
  - sudo /tmp/harmonic-installer.sh -iv
  - echo "------------------- Harmonic Installer - Install Script (COMPLETED) ------------------"
  - echo "------------------- Harmonic Installer - Rebooting System ------------------"
  - sudo shutdown -r now
