#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: harmonic-live
    username: ubuntu
    password: $6$canonical.$0zWaW71A9ke9ASsaOcFTdQ2tx1gSmLxMPrsH0rF0Yb.2AEKNPV1lrF94n6YuPJmnUy2K2/JSDtxuiBDey6Lpa/
  early_commands:
    10-sudo: ["sh", "-c", "echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /target/etc/sudoers.d/ubuntu"]
    20-rootlogin: ["sh", "-c", "sed -i -e '/^[#]*PermitRootLogin/s/^.*$/PermitRootLogin yes/' /target/etc/ssh/sshd_config"]
    30-pwlogin: ["sh", "-c", "sed -i -e '/^[#]*PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /target/etc/ssh/sshd_config"]
    40-sshrestart: ["sh", "-c", "sudo systemctl restart ssh"]
    50-authkey: ["sh", "-c", "sudo sed -r -i 's/^.+(ssh-.+)$/\\1/' /root/.ssh/authorized_keys"]
  late_commands:
    10-mkdir: ["sh", "-c", "sudo mkdir -p /run/harmonic"]
    20-download: ["sh", "-c", "wget --no-proxy http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /tmp/harmonic-installer.sh"]
    30-permissions: ["sh", "-c", "chmod +x /tmp/harmonic-installer.sh"]
    40-execute: ["sh", "-c", "sudo /tmp/harmonic-installer.sh -iv"]
    50-reboot: ["sh", "-c", "sudo shutdown -r now"]
