#cloud-config
users:
  - name: root
    lock_passwd: false
    plain_text_passwd: ubuntu
    ssh_redirect_user: false
    ssh_pwauth: true
    disable_root: false
    preserve_hostname: true
bootcmd:
  - echo "---------------- Harmonic Installer - Update Sudoers (Add 'ubuntu' user with 'ALL=(ALL) NOPASSWD:ALL') -----------------"
  - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu
  - echo "---------------- Harmonic Installer - Configure SSHd (Allow Root Login) -----------------"
  - sed -i -e '/^[#]*PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - echo "---------------- Harmonic Installer - Configure SSHd (Allow Password Login) -----------------"
  - sed -i -e '/^[#]*PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - echo "---------------- Harmonic Installer - Setup (RESTARTING SSHd) -----------------"
  - systemctl restart ssh
  - echo "---------------- Harmonic Installer - Install Script (DOWNLOAD) -----------------"
  - wget http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /media/root-rw/harmonic-installer.sh
  - chmod +x /media/root-rw/harmonic-installer.sh
  - echo "---------------- Harmonic Installer - Install Script (RUNNING) -----------------"
  - /media/root-rw/harmonic-installer.sh -vi
  - echo "------------------- Harmonic Installer - Install Script (COMPLETED) ------------------"
  - echo "------------------- Harmonic Installer - Rebooting System ------------------"
  - shutdown -r now