#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: harmonic-live
    username: ubuntu
    password: $6$canonical.$0zWaW71A9ke9ASsaOcFTdQ2tx1gSmLxMPrsH0rF0Yb.2AEKNPV1lrF94n6YuPJmnUy2K2/JSDtxuiBDey6Lpa/
  keyboard:
    layout: us
    variant: ""
  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: ['ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMeG6n43ekQdEDQAIH4ItQkuCO8KUt10EiIr1Z1psCjG']
  storage:
    grub:
      update_nvram: true
    layout:
      name: direct
  package_update: false
  package_upgrade: false
  early_commands:
    00_harmonic_01: ["/bin/sh", "-c", "sed -r -i 's/^.+(ssh-.+)$/\1/' /root/.ssh/authorized_keys"]
  late_commands:
    00_harmonic_01: ["curtin", "in-target", "--", "wget", "--no-proxy", "http://172.22.31.150:8080/scripts/harmonic-installer.sh", "-O", "/tmp/harmonic-installer.sh"]
    00_harmonic_02: ["curtin", "in-target", "--", "chmod", "+x", "/tmp/harmonic-installer.sh"]
    00_harmonic_03: ["curtin", "in-target", "--", "/bin/bash", "-c", "/tmp/harmonic-installer.sh -iv"]
    00_harmonic_04: ["wget", "--no-proxy", "{{node_disable_pxe_url|escape.json}}", "--post-data", "{{node_disable_pxe_data|escape.json}}", "-O", "/dev/null"]
    00_harmonic_05: ["curtin", "in-target", "--", "poweroff"]
    # 00_harmonic_05: ["shutdown", "-r", "now"]
  user-data:
    runcmd:
      - echo "---------------- Harmonic Installer - Install Script (DOWNLOAD) -----------------"
      - sudo wget http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /tmp/harmonic-installer.sh
      - sudo chmod +x /tmp/harmonic-installer.sh
      - echo "---------------- Harmonic Installer - Install Script (RUNNING) -----------------"
      - sudo /tmp/harmonic-installer.sh -iv
      - echo "------------------- Harmonic Installer - Install Script (COMPLETED) ------------------"
      - echo "------------------- Harmonic Installer - Rebooting System ------------------"
      - sudo poweroff
