#cloud-config
autoinstall:
  early-commands:
  - echo "---------------- Harmonic Installer - Install Script (DOWNLOAD) -----------------"
  - wget http://172.22.31.150:8080/scripts/harmonic-installer.sh -O /media/root-rw/harmonic-installer.sh
  - chmod +x /media/root-rw/harmonic-installer.sh
  - echo "---------------- Harmonic Installer - Install Script (RUNNING) -----------------"
  - /media/root-rw/harmonic-installer.sh -vi
  - echo "------------------- Harmonic Installer - Install Script (COMPLETED) ------------------"
  - echo "------------------- Harmonic Installer - Rebooting System -----------------"
  - shutdown -r now
